
spring:
  profiles:
    active: - dev

---

spring:
  profiles:
    active: dev
  application:
    name: microsevicecloud-config-atguigu-dev

---

spring:
  profiles:
    active: test
  application:
    name: microsevicecloud-config-atguigu-test
