
spring:
  profiles:
    active: 
    - dev

---

spring:
  profiles:
    active: dev
  application:
    name: microsevicecloud-config-aaaa-atguigu-dev

---

spring:
  profiles:
    active: test
  application:
    name: microsevicecloud-config-aaaa-atguigu-test
