spring:
  profiles:
    active: 
    - dev

---

spring:
  profiles: dev
  application:
    name: microsevicecloud-config-atguigu-dev

---

spring:
  profiles: test
  application:
    name: microsevicecloud-config-atguigu-test
